version: "3.8"

services:
  app:
    build: .
    working_dir: /himawari-blog-nuxt
    ports:
      - "3000:3000"
    tty: true
    environment:
      - NODE_ENV=production
    command: ["yarn", "start"]

