version: "3"
services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress_prod
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress_prod
       MYSQL_PASSWORD: prod_wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress_prod
       WORDPRESS_DB_PASSWORD: prod_wordpress
     extra_hosts:
       - "hosts.docker.internal:host-gateway"
     volumes:
       - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
       - wp-plugins:/var/www/html/cms/wp-content/plugins
       - wp-uploads:/var/www/html/cms/wp-content/uploads
       - wp-themes:/var/www/html/cms/wp-content/themes
     working_dir: "/var/www/html/cms"
   reverse-proxy:
    image: nginx:alpine
    restart: always
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./404:/usr/share/nginx/html
      - letsencrypt-cert:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  letsencrypt-cert:
    external: true
  db_data:
  wp-plugins:
  wp-uploads:
  wp-themes:
