name: EC2 auto deploy

# アクションが実行されるタイミングを設定。今回はmainブランチにpushされた時。
on:
 push:
   branches:
     - main
 
#実行される処理
jobs:
 build:
   # 実行環境の指定
   runs-on: ubuntu-latest
   steps:

     # デプロイする
     - name: Deploy
       run: |
         echo "${{ secrets.PRIVATE_KEY }}" > private_key
         chmod 600 private_key
         ssh -p 22 -o "StrictHostKeyChecking=no" -o "ConnectTimeout 600" -oProxyCommand='ssh -W %h:%p ${{ secrets.USER_NAME }}@${{ secrets.SPRINGBOARD_HOST_NAME }} -i private_key -tt' ${{ secrets.USER_NAME }}@${{ secrets.SPRINGBOARD_HOST_NAME }} -i private_key -p 22 "
         echo "remote connected"
         cd apps/wordpress 
         git fetch github:himawari-aerobytes/himawari-blog-nuxt.git
         git pull github:himawari-aerobytes/himawari-blog-nuxt.git
         cd himawari-blog-nuxt && docker-compose up -d
         "
        
         