name: EC2 auto deploy

# アクションが実行されるタイミングを設定。今回はmainブランチにpushされた時。
on:
 push:
   branches:
     - main
 
#実行される処理
jobs:
 build:
   # 実行環境の指定
   runs-on: ubuntu-latest
   steps:

     # デプロイする
     - name: Deploy
       uses: appleboy/ssh-action@v1.0.1
       with:
         proxy_host: ${{ secrets.SPRINGBOARD_HOST_NAME }}
         proxy_username: ${{ secrets.USER_NAME }}
         proxy_key: ${{ secrets.PRIVATE_KEY }}
         host: ${{ secrets.HOST_NAME }}
         username: ${{ secrets.USER_NAME }}
         key: ${{ secrets.PRIVATE_KEY }}
         script: |
          echo "remote connected"
          cd apps/wordpress/himawari-blog-nuxt 
          git pull
          docker-compose up -d --build
          docker image prune -f
          docker builder prune -f
        
         